/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.logic.evoLogicLanguage.impl;

import de.evorepair.logic.evoLogicLanguage.EvoAbstractTerm;
import de.evorepair.logic.evoLogicLanguage.EvoFormula;
import de.evorepair.logic.evoLogicLanguage.EvoLogicLanguagePackage;
import de.evorepair.logic.evoLogicLanguage.EvoVariable;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Evo Formula</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.evorepair.logic.evoLogicLanguage.impl.EvoFormulaImpl#getVariables <em>Variables</em>}</li>
 *   <li>{@link de.evorepair.logic.evoLogicLanguage.impl.EvoFormulaImpl#getTerm <em>Term</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EvoFormulaImpl extends MinimalEObjectImpl.Container implements EvoFormula
{
  /**
   * The cached value of the '{@link #getVariables() <em>Variables</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariables()
   * @generated
   * @ordered
   */
  protected EList<EvoVariable> variables;

  /**
   * The cached value of the '{@link #getTerm() <em>Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTerm()
   * @generated
   * @ordered
   */
  protected EvoAbstractTerm term;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EvoFormulaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EvoLogicLanguagePackage.Literals.EVO_FORMULA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<EvoVariable> getVariables()
  {
    if (variables == null)
    {
      variables = new EObjectContainmentEList<EvoVariable>(EvoVariable.class, this, EvoLogicLanguagePackage.EVO_FORMULA__VARIABLES);
    }
    return variables;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EvoAbstractTerm getTerm()
  {
    return term;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTerm(EvoAbstractTerm newTerm, NotificationChain msgs)
  {
    EvoAbstractTerm oldTerm = term;
    term = newTerm;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EvoLogicLanguagePackage.EVO_FORMULA__TERM, oldTerm, newTerm);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTerm(EvoAbstractTerm newTerm)
  {
    if (newTerm != term)
    {
      NotificationChain msgs = null;
      if (term != null)
        msgs = ((InternalEObject)term).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EvoLogicLanguagePackage.EVO_FORMULA__TERM, null, msgs);
      if (newTerm != null)
        msgs = ((InternalEObject)newTerm).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EvoLogicLanguagePackage.EVO_FORMULA__TERM, null, msgs);
      msgs = basicSetTerm(newTerm, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EvoLogicLanguagePackage.EVO_FORMULA__TERM, newTerm, newTerm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EvoLogicLanguagePackage.EVO_FORMULA__VARIABLES:
        return ((InternalEList<?>)getVariables()).basicRemove(otherEnd, msgs);
      case EvoLogicLanguagePackage.EVO_FORMULA__TERM:
        return basicSetTerm(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EvoLogicLanguagePackage.EVO_FORMULA__VARIABLES:
        return getVariables();
      case EvoLogicLanguagePackage.EVO_FORMULA__TERM:
        return getTerm();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EvoLogicLanguagePackage.EVO_FORMULA__VARIABLES:
        getVariables().clear();
        getVariables().addAll((Collection<? extends EvoVariable>)newValue);
        return;
      case EvoLogicLanguagePackage.EVO_FORMULA__TERM:
        setTerm((EvoAbstractTerm)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EvoLogicLanguagePackage.EVO_FORMULA__VARIABLES:
        getVariables().clear();
        return;
      case EvoLogicLanguagePackage.EVO_FORMULA__TERM:
        setTerm((EvoAbstractTerm)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EvoLogicLanguagePackage.EVO_FORMULA__VARIABLES:
        return variables != null && !variables.isEmpty();
      case EvoLogicLanguagePackage.EVO_FORMULA__TERM:
        return term != null;
    }
    return super.eIsSet(featureID);
  }

} //EvoFormulaImpl
