/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.logic.evoLogicLanguage.impl;

import de.evorepair.logic.evoLogicLanguage.EvoLogicLanguagePackage;
import de.evorepair.logic.evoLogicLanguage.EvoVariable;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Evo Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EvoVariableImpl extends MinimalEObjectImpl.Container implements EvoVariable
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EvoVariableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EvoLogicLanguagePackage.Literals.EVO_VARIABLE;
  }

} //EvoVariableImpl
