/*
 * generated by Xtext 2.11.0
 */
package de.evorepair.logic.ui;

import com.google.inject.Injector;
import de.evorepair.logic.language.ui.internal.LanguageActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EvoLogicLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LanguageActivator.getInstance().getInjector(LanguageActivator.DE_EVOREPAIR_LOGIC_EVOLOGICLANGUAGE);
	}
	
}
