/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.evolution.variable.tests;

import com.google.inject.Inject;
import de.evorepair.evolution.variable.evoVariableDsl.Model;
import de.evorepair.evolution.variable.tests.EvoVariableDslInjectorProvider;
import org.junit.Test;
import org.junit.runner.RunWith;

/* @RunWith(/* name is null */)
@InjectWith(EvoVariableDslInjectorProvider.class) */@SuppressWarnings("all")
public class EvoVariableDslParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field EvoVariableDslParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
