/*
 * generated by Xtext 2.11.0
 */
package de.evorepair.logic.ui.tests;

import com.google.inject.Injector;
import de.evorepair.logic.language.ui.internal.LanguageActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EvoLogicLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LanguageActivator.getInstance().getInjector("de.evorepair.logic.EvoLogicLanguage");
	}

}
