/*
 * generated by Xtext 2.12.0
 */
package de.evorepair.guidance


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EvoGuidanceDslRuntimeModule extends AbstractEvoGuidanceDslRuntimeModule {
}
