/*
 * generated by Xtext 2.11.0
 */
package de.evorepair.logic


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EvoLogicLanguageStandaloneSetup extends EvoLogicLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new EvoLogicLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
