/**
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.expression.ui.contentassist;

import de.evorepair.feature.expression.ui.contentassist.AbstractEvoExpressionDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EvoExpressionDslProposalProvider extends AbstractEvoExpressionDslProposalProvider {
}
