/*
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.expression.scoping;

import de.evorepair.logic.scoping.EvoLogicDslScopeProvider;

public abstract class AbstractEvoExpressionDslScopeProvider extends EvoLogicDslScopeProvider {
}
