/**
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.expression.ide;

import com.google.inject.Injector;
import de.evorepair.feature.expression.EvoExpressionDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EvoExpressionDslIdeSetup extends EvoExpressionDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from EvoExpressionDslRuntimeModule to Module"
      + "\nType mismatch: cannot convert from EvoExpressionDslIdeModule to Module");
  }
}
