<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="evofirstorderlogic" nsURI="http://darwinspl.de/evorepair/logic/0.3"
    nsPrefix="evofirstorderlogic">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="configuration" value="../../eu.hyvar.feature.configuration/model/Configuration.ecore#/"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="evooperation_0" value="../../de.evorepair.evolution.operation/model/EvoOperation.ecore#/"/>
    <details key="evovariable_0" value="../../de.evorepair.evolution.variable/model/EvoVariable.ecore#/"/>
    <details key="feature_0" value="../../eu.hyvar.feature/model/Feature.ecore#/"/>
    <details key="mapping_0" value="../../eu.hyvar.feature.mapping/model/Mapping.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAnd" eSuperTypes="#//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoOr" eSuperTypes="#//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAbstractTwoParameterTerm" abstract="true"
      interface="true" eSuperTypes="#//EvoAbstractTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftElement" lowerBound="1"
        eType="#//EvoAbstractTerm" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightElement" lowerBound="1"
        eType="#//EvoAbstractTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoXOr" eSuperTypes="#//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoNot" eSuperTypes="#//EvoAbstractOneParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAbstractOneParameterTerm" abstract="true"
      interface="true" eSuperTypes="#//EvoAbstractTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//EvoAbstractTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAbstractTerm" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoEqual" eSuperTypes="#//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoUnequal" eSuperTypes="#//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoImplication" eSuperTypes="#//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoBiconditional" eSuperTypes="#//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoFormulaVariable" abstract="true"
      eSuperTypes="#//EvoAbstractTerm ../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoFormulaSetVariable" abstract="true"
      eSuperTypes="../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoSetVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAbstractSetTerm" abstract="true"
      eSuperTypes="#//EvoAbstractTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetInclusion" eSuperTypes="#//EvoAbstractSetTerm #//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetIntersection" eSuperTypes="#//EvoAbstractSetTerm #//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetUnion" eSuperTypes="#//EvoAbstractSetTerm #//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetDifference" eSuperTypes="#//EvoAbstractSetTerm #//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetSymmetricDifference" eSuperTypes="#//EvoAbstractSetTerm #//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetCartesianProduct" eSuperTypes="#//EvoAbstractSetTerm #//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetCardinality" eSuperTypes="#//EvoAbstractSetTerm #//EvoAbstractOneParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetElementOf" eSuperTypes="#//EvoAbstractSetTerm #//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetNotElementOf" eSuperTypes="#//EvoAbstractSetTerm #//EvoAbstractTwoParameterTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAbstractQuantifierTerm" abstract="true"
      interface="true" eSuperTypes="#//EvoAbstractTerm #//EvoAbstractOneParameterTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundedVariable" lowerBound="1"
        eType="#//EvoEvolutionTerm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoForAll" eSuperTypes="#//EvoAbstractQuantifierTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoExist" eSuperTypes="#//EvoAbstractQuantifierTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoUniqueExists" eSuperTypes="#//EvoAbstractQuantifierTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoFormula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" lowerBound="1" eType="#//EvoAbstractTerm"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//EvoEvolutionTerm" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testTrigger" eType="ecore:EClass ../../de.evorepair.evolution.operation/model/EvoOperation.ecore#//EvoOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoVariableTerm" eSuperTypes="#//EvoAbstractTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="ecore:EClass ../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoVariable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoVariableType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoApplicationConstraintTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass ../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoMappingVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoApplicationConstraintVariable" eSuperTypes="#//EvoEvolutionTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" eType="#//EvoMappingVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoFeatureModelConstraintVariable" eSuperTypes="#//EvoEvolutionTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoPredefinedVariable" eSuperTypes="#//EvoEvolutionTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAllFeaturesVariable" eSuperTypes="#//EvoEvolutionTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAllMappingsVariable" eSuperTypes="#//EvoAbstractTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//EvoAbstractTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoMappingAssociatedAssetsVariable"
      eSuperTypes="#//EvoEvolutionTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="associatedMapping" eType="#//EvoMappingVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoMappingVariable" eSuperTypes="#//EvoPredefinedVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapping" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingFeature" eType="#//EvoFormulaVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoInvolvedFeatureVariable" eSuperTypes="#//EvoEvolutionTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoRequirementVariable" eSuperTypes="#//EvoPredefinedVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSize" eSuperTypes="#//EvoAbstractTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoGroupType" eSuperTypes="#//EvoEvolutionTerm #//EvoAbstractTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../eu.hyvar.feature/model/Feature.ecore#//HyGroupTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoGroupVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoFeatureType" eSuperTypes="#//EvoAbstractTerm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../eu.hyvar.feature/model/Feature.ecore#//HyFeatureTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoFeatureVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoEvolutionTerm" eSuperTypes="../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="afterEvolution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSiblings" eSuperTypes="#//EvoPredefinedVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../eu.hyvar.feature/model/Feature.ecore#//HyFeatureTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSatisfiable" eSuperTypes="#//EvoAbstractTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
        upperBound="-1" eType="#//EvoAbstractTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetTerm" eSuperTypes="#//EvoAbstractOneParameterTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//EvoAbstractTerm" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
