<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="evologic" nsURI="http://darwinspl.de/evorepair/logic/0.4" nsPrefix="evologic">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="configuration" value="../../eu.hyvar.feature.configuration/model/Configuration.ecore#/"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="evooperation_0" value="../../de.evorepair.evolution.operation/model/EvoOperation.ecore#/"/>
    <details key="evovariable_0" value="../../de.evorepair.evolution.variable/model/EvoVariable.ecore#/"/>
    <details key="expression_0" value="../../eu.hyvar.feature.expression/model/Expression.ecore#/"/>
    <details key="feature_0" value="../../eu.hyvar.feature/model/Feature.ecore#/"/>
    <details key="mapping_0" value="../../eu.hyvar.feature.mapping/model/Mapping.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EvoBinaryExpression" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoXOr" eSuperTypes="#//EvoBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoNot" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyUnaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoBiconditional" eSuperTypes="#//EvoBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoFormulaVariable" abstract="true"
      eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression ../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoFormulaSetVariable" abstract="true"
      eSuperTypes="../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoSetVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAbstractSetTerm" abstract="true"
      eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetInclusion" eSuperTypes="#//EvoAbstractSetTerm #//EvoBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetIntersection" eSuperTypes="#//EvoAbstractSetTerm #//EvoBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetUnion" eSuperTypes="#//EvoAbstractSetTerm #//EvoBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetDifference" eSuperTypes="#//EvoAbstractSetTerm #//EvoBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetSymmetricDifference" eSuperTypes="#//EvoAbstractSetTerm #//EvoBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetCartesianProduct" eSuperTypes="#//EvoAbstractSetTerm #//EvoBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetCardinality" eSuperTypes="#//EvoAbstractSetTerm ../../eu.hyvar.feature.expression/model/Expression.ecore#//HyUnaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoElementOf" eSuperTypes="#//EvoAbstractSetTerm #//EvoBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetNotElementOf" eSuperTypes="#//EvoAbstractSetTerm #//EvoBinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAbstractQuantifierTerm" abstract="true"
      interface="true" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression ../../eu.hyvar.feature.expression/model/Expression.ecore#//HyUnaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boundedVariables" lowerBound="1"
        upperBound="-1" eType="#//EvoVariableTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoForAll" eSuperTypes="#//EvoAbstractQuantifierTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoExist" eSuperTypes="#//EvoAbstractQuantifierTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoUniqueExists" eSuperTypes="#//EvoAbstractQuantifierTerm"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoFormula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" lowerBound="1" eType="ecore:EClass ../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoVariableTerm" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="ecore:EClass ../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoVariable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoVariableType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoApplicationConstraintTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass ../../de.evorepair.evolution.variable/model/EvoVariable.ecore#//EvoMappingVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSize" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoGroupType" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../eu.hyvar.feature/model/Feature.ecore#//HyGroupTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
        upperBound="-1" eType="#//EvoVariableTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoFeatureType" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../eu.hyvar.feature/model/Feature.ecore#//HyFeatureTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
        upperBound="-1" eType="#//EvoVariableTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSatisfiable" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSetTerm" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="ecore:EClass ../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoChildrenOf" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//EvoVariableTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoSiblingsOf" eSuperTypes="#//EvoSetTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//EvoVariableTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoParentOf" eSuperTypes="#//EvoSetTerm">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//EvoVariableTerm" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAllMappings" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvoAllConfigurations" eSuperTypes="../../eu.hyvar.feature.expression/model/Expression.ecore#//HyExpression"/>
</ecore:EPackage>
