/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.evolution.variable;

import de.evorepair.evolution.variable.EvoVariableDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EvoVariableDslStandaloneSetup extends EvoVariableDslStandaloneSetupGenerated {
  public static void doSetup() {
    new EvoVariableDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
