/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.evolution.operation.ui.contentassist;

import de.evorepair.evolution.operation.ui.contentassist.AbstractEvoOperationDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EvoOperationDslProposalProvider extends AbstractEvoOperationDslProposalProvider {
}
