/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.operation.evoOperationDsl.impl;

import de.evorepair.operation.evoOperationDsl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class EvoOperationDslFactoryImpl extends EFactoryImpl implements EvoOperationDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static EvoOperationDslFactory init()
  {
    try
    {
      EvoOperationDslFactory theEvoOperationDslFactory = (EvoOperationDslFactory)EPackage.Registry.INSTANCE.getEFactory(EvoOperationDslPackage.eNS_URI);
      if (theEvoOperationDslFactory != null)
      {
        return theEvoOperationDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new EvoOperationDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EvoOperationDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case EvoOperationDslPackage.GRAMMAR_ENTRY: return createGrammarEntry();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GrammarEntry createGrammarEntry()
  {
    GrammarEntryImpl grammarEntry = new GrammarEntryImpl();
    return grammarEntry;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EvoOperationDslPackage getEvoOperationDslPackage()
  {
    return (EvoOperationDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static EvoOperationDslPackage getPackage()
  {
    return EvoOperationDslPackage.eINSTANCE;
  }

} //EvoOperationDslFactoryImpl
