/*
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.mapping.validation;

import de.evorepair.feature.expression.validation.EvoExpressionDslValidator;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public abstract class AbstractDwMappingDslValidator extends EvoExpressionDslValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://hyvar-project.eu/feature/mapping/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://deltaecore.org/decore/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://hyvar-project.eu/feature/expression/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://hyvar-project.eu/feature/dataValues/1.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://darwinspl.de/evorepair/logic/0.4"));
		return result;
	}
	
}
