/**
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.expression.evo_expression_dsl;

import de.evorepair.logic.evo_logic_dsl.Evo_logic_dslPackage;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.evorepair.feature.expression.evo_expression_dsl.Evo_expression_dslFactory
 * @model kind="package"
 * @generated
 */
public interface Evo_expression_dslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "evo_expression_dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://darwinspl.de/evorepair/feature/expression/dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "evo_expression_dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Evo_expression_dslPackage eINSTANCE = de.evorepair.feature.expression.evo_expression_dsl.impl.Evo_expression_dslPackageImpl.init();

  /**
   * The meta object id for the '{@link de.evorepair.feature.expression.evo_expression_dsl.impl.GrammarEntryImpl <em>Grammar Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.feature.expression.evo_expression_dsl.impl.GrammarEntryImpl
   * @see de.evorepair.feature.expression.evo_expression_dsl.impl.Evo_expression_dslPackageImpl#getGrammarEntry()
   * @generated
   */
  int GRAMMAR_ENTRY = 0;

  /**
   * The feature id for the '<em><b>Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAMMAR_ENTRY__FORMULA = Evo_logic_dslPackage.GRAMMAR_ENTRY__FORMULA;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAMMAR_ENTRY__EXPRESSION = Evo_logic_dslPackage.GRAMMAR_ENTRY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Grammar Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAMMAR_ENTRY_FEATURE_COUNT = Evo_logic_dslPackage.GRAMMAR_ENTRY_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link de.evorepair.feature.expression.evo_expression_dsl.GrammarEntry <em>Grammar Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grammar Entry</em>'.
   * @see de.evorepair.feature.expression.evo_expression_dsl.GrammarEntry
   * @generated
   */
  EClass getGrammarEntry();

  /**
   * Returns the meta object for the containment reference '{@link de.evorepair.feature.expression.evo_expression_dsl.GrammarEntry#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see de.evorepair.feature.expression.evo_expression_dsl.GrammarEntry#getExpression()
   * @see #getGrammarEntry()
   * @generated
   */
  EReference getGrammarEntry_Expression();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Evo_expression_dslFactory getEvo_expression_dslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.evorepair.feature.expression.evo_expression_dsl.impl.GrammarEntryImpl <em>Grammar Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.feature.expression.evo_expression_dsl.impl.GrammarEntryImpl
     * @see de.evorepair.feature.expression.evo_expression_dsl.impl.Evo_expression_dslPackageImpl#getGrammarEntry()
     * @generated
     */
    EClass GRAMMAR_ENTRY = eINSTANCE.getGrammarEntry();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAMMAR_ENTRY__EXPRESSION = eINSTANCE.getGrammarEntry_Expression();

  }

} //Evo_expression_dslPackage
