/**
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.expression.evo_expression_dsl;

import eu.hyvar.feature.expression.HyExpression;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Evo Implication</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.evorepair.feature.expression.evo_expression_dsl.EvoImplication#getOperand1 <em>Operand1</em>}</li>
 *   <li>{@link de.evorepair.feature.expression.evo_expression_dsl.EvoImplication#getOperand2 <em>Operand2</em>}</li>
 * </ul>
 *
 * @see de.evorepair.feature.expression.evo_expression_dsl.Evo_expression_dslPackage#getEvoImplication()
 * @model
 * @generated
 */
public interface EvoImplication extends HyExpression
{
  /**
   * Returns the value of the '<em><b>Operand1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operand1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operand1</em>' containment reference.
   * @see #setOperand1(HyExpression)
   * @see de.evorepair.feature.expression.evo_expression_dsl.Evo_expression_dslPackage#getEvoImplication_Operand1()
   * @model containment="true"
   * @generated
   */
  HyExpression getOperand1();

  /**
   * Sets the value of the '{@link de.evorepair.feature.expression.evo_expression_dsl.EvoImplication#getOperand1 <em>Operand1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operand1</em>' containment reference.
   * @see #getOperand1()
   * @generated
   */
  void setOperand1(HyExpression value);

  /**
   * Returns the value of the '<em><b>Operand2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operand2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operand2</em>' containment reference.
   * @see #setOperand2(HyExpression)
   * @see de.evorepair.feature.expression.evo_expression_dsl.Evo_expression_dslPackage#getEvoImplication_Operand2()
   * @model containment="true"
   * @generated
   */
  HyExpression getOperand2();

  /**
   * Sets the value of the '{@link de.evorepair.feature.expression.evo_expression_dsl.EvoImplication#getOperand2 <em>Operand2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operand2</em>' containment reference.
   * @see #getOperand2()
   * @generated
   */
  void setOperand2(HyExpression value);

} // EvoImplication
