/*
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.mapping.parser.antlr;

import com.google.inject.Inject;
import de.evorepair.feature.mapping.parser.antlr.internal.InternalDwMappingDslParser;
import de.evorepair.feature.mapping.services.DwMappingDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DwMappingDslParser extends AbstractAntlrParser {

	@Inject
	private DwMappingDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDwMappingDslParser createParser(XtextTokenStream stream) {
		return new InternalDwMappingDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "HyMappingModel";
	}

	public DwMappingDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DwMappingDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
