/*
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.expression.ui.tests;

import com.google.inject.Injector;
import de.evorepair.feature.expression.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ExpressionDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("de.evorepair.feature.expression.ExpressionDsl");
	}

}
