/**
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.expression.evo_expression_dsl.impl;

import de.evorepair.evolution.evovariable.EvoVariablePackage;

import de.evorepair.feature.expression.evo_expression_dsl.EvoImplication;
import de.evorepair.feature.expression.evo_expression_dsl.EvoSetElementOf;
import de.evorepair.feature.expression.evo_expression_dsl.Evo_expression_dslFactory;
import de.evorepair.feature.expression.evo_expression_dsl.Evo_expression_dslPackage;
import de.evorepair.feature.expression.evo_expression_dsl.GrammarEntry;
import de.evorepair.feature.expression.evo_expression_dsl.HyFeatureReferenceExpression;

import de.evorepair.logic.evoLogicDsl.EvoLogicDslPackage;

import de.evorepair.logic.evologic.EvoLogicPackage;

import eu.hyvar.context.HyContextInformationPackage;

import eu.hyvar.dataValues.HyDataValuesPackage;

import eu.hyvar.evolution.HyEvolutionPackage;

import eu.hyvar.feature.HyFeaturePackage;

import eu.hyvar.feature.configuration.HyConfigurationPackage;

import eu.hyvar.feature.expression.HyExpressionPackage;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class Evo_expression_dslPackageImpl extends EPackageImpl implements Evo_expression_dslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass grammarEntryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass hyFeatureReferenceExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass evoSetElementOfEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass evoImplicationEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see de.evorepair.feature.expression.evo_expression_dsl.Evo_expression_dslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private Evo_expression_dslPackageImpl()
  {
    super(eNS_URI, Evo_expression_dslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link Evo_expression_dslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static Evo_expression_dslPackage init()
  {
    if (isInited) return (Evo_expression_dslPackage)EPackage.Registry.INSTANCE.getEPackage(Evo_expression_dslPackage.eNS_URI);

    // Obtain or create and register package
    Evo_expression_dslPackageImpl theEvo_expression_dslPackage = (Evo_expression_dslPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof Evo_expression_dslPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new Evo_expression_dslPackageImpl());

    isInited = true;

    // Initialize simple dependencies
    EvoLogicDslPackage.eINSTANCE.eClass();
    HyExpressionPackage.eINSTANCE.eClass();
    HyFeaturePackage.eINSTANCE.eClass();
    EvoLogicPackage.eINSTANCE.eClass();
    EvoVariablePackage.eINSTANCE.eClass();
    HyDataValuesPackage.eINSTANCE.eClass();
    HyContextInformationPackage.eINSTANCE.eClass();
    HyEvolutionPackage.eINSTANCE.eClass();
    HyConfigurationPackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theEvo_expression_dslPackage.createPackageContents();

    // Initialize created meta-data
    theEvo_expression_dslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theEvo_expression_dslPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(Evo_expression_dslPackage.eNS_URI, theEvo_expression_dslPackage);
    return theEvo_expression_dslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getGrammarEntry()
  {
    return grammarEntryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getGrammarEntry_Expression()
  {
    return (EReference)grammarEntryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getHyFeatureReferenceExpression()
  {
    return hyFeatureReferenceExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getHyFeatureReferenceExpression_Feature()
  {
    return (EReference)hyFeatureReferenceExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEvoSetElementOf()
  {
    return evoSetElementOfEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEvoSetElementOf_Operand1()
  {
    return (EReference)evoSetElementOfEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEvoSetElementOf_Operand2()
  {
    return (EReference)evoSetElementOfEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getEvoImplication()
  {
    return evoImplicationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEvoImplication_Operand1()
  {
    return (EReference)evoImplicationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getEvoImplication_Operand2()
  {
    return (EReference)evoImplicationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Evo_expression_dslFactory getEvo_expression_dslFactory()
  {
    return (Evo_expression_dslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    grammarEntryEClass = createEClass(GRAMMAR_ENTRY);
    createEReference(grammarEntryEClass, GRAMMAR_ENTRY__EXPRESSION);

    hyFeatureReferenceExpressionEClass = createEClass(HY_FEATURE_REFERENCE_EXPRESSION);
    createEReference(hyFeatureReferenceExpressionEClass, HY_FEATURE_REFERENCE_EXPRESSION__FEATURE);

    evoSetElementOfEClass = createEClass(EVO_SET_ELEMENT_OF);
    createEReference(evoSetElementOfEClass, EVO_SET_ELEMENT_OF__OPERAND1);
    createEReference(evoSetElementOfEClass, EVO_SET_ELEMENT_OF__OPERAND2);

    evoImplicationEClass = createEClass(EVO_IMPLICATION);
    createEReference(evoImplicationEClass, EVO_IMPLICATION__OPERAND1);
    createEReference(evoImplicationEClass, EVO_IMPLICATION__OPERAND2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    EvoLogicDslPackage theEvoLogicDslPackage = (EvoLogicDslPackage)EPackage.Registry.INSTANCE.getEPackage(EvoLogicDslPackage.eNS_URI);
    HyExpressionPackage theHyExpressionPackage = (HyExpressionPackage)EPackage.Registry.INSTANCE.getEPackage(HyExpressionPackage.eNS_URI);
    HyFeaturePackage theHyFeaturePackage = (HyFeaturePackage)EPackage.Registry.INSTANCE.getEPackage(HyFeaturePackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    grammarEntryEClass.getESuperTypes().add(theEvoLogicDslPackage.getGrammarEntry());
    hyFeatureReferenceExpressionEClass.getESuperTypes().add(theHyExpressionPackage.getHyExpression());
    evoSetElementOfEClass.getESuperTypes().add(theHyExpressionPackage.getHyExpression());
    evoImplicationEClass.getESuperTypes().add(theHyExpressionPackage.getHyExpression());

    // Initialize classes and features; add operations and parameters
    initEClass(grammarEntryEClass, GrammarEntry.class, "GrammarEntry", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGrammarEntry_Expression(), theHyExpressionPackage.getHyExpression(), null, "expression", null, 0, 1, GrammarEntry.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(hyFeatureReferenceExpressionEClass, HyFeatureReferenceExpression.class, "HyFeatureReferenceExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getHyFeatureReferenceExpression_Feature(), theHyFeaturePackage.getHyFeature(), null, "feature", null, 0, 1, HyFeatureReferenceExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(evoSetElementOfEClass, EvoSetElementOf.class, "EvoSetElementOf", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEvoSetElementOf_Operand1(), theHyExpressionPackage.getHyExpression(), null, "operand1", null, 0, 1, EvoSetElementOf.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEvoSetElementOf_Operand2(), theHyExpressionPackage.getHyExpression(), null, "operand2", null, 0, 1, EvoSetElementOf.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(evoImplicationEClass, EvoImplication.class, "EvoImplication", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getEvoImplication_Operand1(), theHyExpressionPackage.getHyExpression(), null, "operand1", null, 0, 1, EvoImplication.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getEvoImplication_Operand2(), theHyExpressionPackage.getHyExpression(), null, "operand2", null, 0, 1, EvoImplication.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //Evo_expression_dslPackageImpl
