/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.operation.evoOperationDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.evorepair.operation.evoOperationDsl.EvoOperationDslPackage
 * @generated
 */
public interface EvoOperationDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EvoOperationDslFactory eINSTANCE = de.evorepair.operation.evoOperationDsl.impl.EvoOperationDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Grammar Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Grammar Entry</em>'.
   * @generated
   */
  GrammarEntry createGrammarEntry();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  EvoOperationDslPackage getEvoOperationDslPackage();

} //EvoOperationDslFactory
