/*
 * generated by Xtext 2.12.0
 */
package de.evorepair.guidance.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class EvoGuidanceDslWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public EvoGuidanceDslWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
