/*
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.mapping


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DwMappingDslStandaloneSetup extends DwMappingDslStandaloneSetupGenerated {

	def static void doSetup() {
		new DwMappingDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
