/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.evolution.variable.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EvoVariableDslIdeModule /* implements AbstractEvoVariableDslIdeModule  */{
}
