/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.evolution.variable.evoVariableDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.evorepair.evolution.variable.evoVariableDsl.EvoVariableDslPackage
 * @generated
 */
public interface EvoVariableDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EvoVariableDslFactory eINSTANCE = de.evorepair.evolution.variable.evoVariableDsl.impl.EvoVariableDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  EvoVariableDslPackage getEvoVariableDslPackage();

} //EvoVariableDslFactory
