/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.evolution.variable.evoVariableDsl;

import de.evorepair.evolution.evovariable.EvoVariablePackage;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.evorepair.evolution.variable.evoVariableDsl.EvoVariableDslFactory
 * @model kind="package"
 * @generated
 */
public interface EvoVariableDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "evoVariableDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.evorepair.de/evolution/variable/EvoVariableDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "evoVariableDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EvoVariableDslPackage eINSTANCE = de.evorepair.evolution.variable.evoVariableDsl.impl.EvoVariableDslPackageImpl.init();

  /**
   * The meta object id for the '{@link de.evorepair.evolution.variable.evoVariableDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.evolution.variable.evoVariableDsl.impl.ModelImpl
   * @see de.evorepair.evolution.variable.evoVariableDsl.impl.EvoVariableDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__VARIABLES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.evorepair.evolution.variable.evoVariableDsl.impl.EvoGenericVariableImpl <em>Evo Generic Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.evolution.variable.evoVariableDsl.impl.EvoGenericVariableImpl
   * @see de.evorepair.evolution.variable.evoVariableDsl.impl.EvoVariableDslPackageImpl#getEvoGenericVariable()
   * @generated
   */
  int EVO_GENERIC_VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_GENERIC_VARIABLE__NAME = EvoVariablePackage.EVO_VARIABLE__NAME;

  /**
   * The feature id for the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_GENERIC_VARIABLE__INDEX = EvoVariablePackage.EVO_VARIABLE__INDEX;

  /**
   * The feature id for the '<em><b>Variable Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_GENERIC_VARIABLE__VARIABLE_TYPE = EvoVariablePackage.EVO_VARIABLE__VARIABLE_TYPE;

  /**
   * The number of structural features of the '<em>Evo Generic Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_GENERIC_VARIABLE_FEATURE_COUNT = EvoVariablePackage.EVO_VARIABLE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link de.evorepair.evolution.variable.evoVariableDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see de.evorepair.evolution.variable.evoVariableDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link de.evorepair.evolution.variable.evoVariableDsl.Model#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see de.evorepair.evolution.variable.evoVariableDsl.Model#getVariables()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Variables();

  /**
   * Returns the meta object for class '{@link de.evorepair.evolution.variable.evoVariableDsl.EvoGenericVariable <em>Evo Generic Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evo Generic Variable</em>'.
   * @see de.evorepair.evolution.variable.evoVariableDsl.EvoGenericVariable
   * @generated
   */
  EClass getEvoGenericVariable();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EvoVariableDslFactory getEvoVariableDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.evorepair.evolution.variable.evoVariableDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.evolution.variable.evoVariableDsl.impl.ModelImpl
     * @see de.evorepair.evolution.variable.evoVariableDsl.impl.EvoVariableDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__VARIABLES = eINSTANCE.getModel_Variables();

    /**
     * The meta object literal for the '{@link de.evorepair.evolution.variable.evoVariableDsl.impl.EvoGenericVariableImpl <em>Evo Generic Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.evolution.variable.evoVariableDsl.impl.EvoGenericVariableImpl
     * @see de.evorepair.evolution.variable.evoVariableDsl.impl.EvoVariableDslPackageImpl#getEvoGenericVariable()
     * @generated
     */
    EClass EVO_GENERIC_VARIABLE = eINSTANCE.getEvoGenericVariable();

  }

} //EvoVariableDslPackage
