/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.evolution.variable.evoVariableDsl;

import de.evorepair.evolution.evovariable.EvoVariable;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.evorepair.evolution.variable.evoVariableDsl.Model#getVariables <em>Variables</em>}</li>
 * </ul>
 *
 * @see de.evorepair.evolution.variable.evoVariableDsl.EvoVariableDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Variables</b></em>' containment reference list.
   * The list contents are of type {@link de.evorepair.evolution.evovariable.EvoVariable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variables</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variables</em>' containment reference list.
   * @see de.evorepair.evolution.variable.evoVariableDsl.EvoVariableDslPackage#getModel_Variables()
   * @model containment="true"
   * @generated
   */
  EList<EvoVariable> getVariables();

} // Model
