/*
 * generated by Xtext 2.11.0
 */
package de.evorepair.logic


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EvoDslStandaloneSetup extends EvoDslStandaloneSetupGenerated {

	def static void doSetup() {
		new EvoDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
