/*
 * generated by Xtext 2.12.0
 */
package de.evorepair.logic


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EvoLogicDslStandaloneSetup extends EvoLogicDslStandaloneSetupGenerated {

	def static void doSetup() {
		new EvoLogicDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
