/*
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.mapping.scoping;

import de.evorepair.feature.expression.scoping.EvoExpressionDslScopeProvider;

public abstract class AbstractDwMappingDslScopeProvider extends EvoExpressionDslScopeProvider {
}
