/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.logic.evoLogicLanguage;

import eu.hyvar.feature.HyFeature;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Evo Arbitraty Feature Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.evorepair.logic.evoLogicLanguage.EvoArbitratyFeatureVariable#getFeature <em>Feature</em>}</li>
 * </ul>
 *
 * @see de.evorepair.logic.evoLogicLanguage.EvoLogicLanguagePackage#getEvoArbitratyFeatureVariable()
 * @model
 * @generated
 */
public interface EvoArbitratyFeatureVariable extends EvoVariable
{
  /**
   * Returns the value of the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' reference.
   * @see #setFeature(HyFeature)
   * @see de.evorepair.logic.evoLogicLanguage.EvoLogicLanguagePackage#getEvoArbitratyFeatureVariable_Feature()
   * @model
   * @generated
   */
  HyFeature getFeature();

  /**
   * Sets the value of the '{@link de.evorepair.logic.evoLogicLanguage.EvoArbitratyFeatureVariable#getFeature <em>Feature</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feature</em>' reference.
   * @see #getFeature()
   * @generated
   */
  void setFeature(HyFeature value);

} // EvoArbitratyFeatureVariable
