/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.logic.evoLogicLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.evorepair.logic.evoLogicLanguage.EvoLogicLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface EvoLogicLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "evoLogicLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://tu-braunschweig.de/isf/darwinspl/evorepair/logic/firstorder";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "evoLogicLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EvoLogicLanguagePackage eINSTANCE = de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link de.evorepair.logic.evoLogicLanguage.impl.CommandDocumentImpl <em>Command Document</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.logic.evoLogicLanguage.impl.CommandDocumentImpl
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getCommandDocument()
   * @generated
   */
  int COMMAND_DOCUMENT = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_DOCUMENT__IMPORTS = 0;

  /**
   * The feature id for the '<em><b>Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_DOCUMENT__FORMULA = 1;

  /**
   * The number of structural features of the '<em>Command Document</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_DOCUMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.evorepair.logic.evoLogicLanguage.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.logic.evoLogicLanguage.impl.ImportImpl
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getImport()
   * @generated
   */
  int IMPORT = 1;

  /**
   * The feature id for the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORT_URI = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoFormulaImpl <em>Evo Formula</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoFormulaImpl
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoFormula()
   * @generated
   */
  int EVO_FORMULA = 2;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_FORMULA__VARIABLES = 0;

  /**
   * The feature id for the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_FORMULA__TERM = 1;

  /**
   * The number of structural features of the '<em>Evo Formula</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_FORMULA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoVariableImpl <em>Evo Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoVariableImpl
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoVariable()
   * @generated
   */
  int EVO_VARIABLE = 3;

  /**
   * The number of structural features of the '<em>Evo Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_VARIABLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoAbstractTermImpl <em>Evo Abstract Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoAbstractTermImpl
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoAbstractTerm()
   * @generated
   */
  int EVO_ABSTRACT_TERM = 6;

  /**
   * The number of structural features of the '<em>Evo Abstract Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_ABSTRACT_TERM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoVariableTermImpl <em>Evo Variable Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoVariableTermImpl
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoVariableTerm()
   * @generated
   */
  int EVO_VARIABLE_TERM = 4;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_VARIABLE_TERM__VARIABLE = EVO_ABSTRACT_TERM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Evo Variable Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_VARIABLE_TERM_FEATURE_COUNT = EVO_ABSTRACT_TERM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoArbitratyFeatureVariableImpl <em>Evo Arbitraty Feature Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoArbitratyFeatureVariableImpl
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoArbitratyFeatureVariable()
   * @generated
   */
  int EVO_ARBITRATY_FEATURE_VARIABLE = 5;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_ARBITRATY_FEATURE_VARIABLE__FEATURE = EVO_VARIABLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Evo Arbitraty Feature Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_ARBITRATY_FEATURE_VARIABLE_FEATURE_COUNT = EVO_VARIABLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoOrImpl <em>Evo Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoOrImpl
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoOr()
   * @generated
   */
  int EVO_OR = 7;

  /**
   * The feature id for the '<em><b>Left Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_OR__LEFT_ELEMENT = EVO_ABSTRACT_TERM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_OR__RIGHT_ELEMENT = EVO_ABSTRACT_TERM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Evo Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_OR_FEATURE_COUNT = EVO_ABSTRACT_TERM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoXOrImpl <em>Evo XOr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoXOrImpl
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoXOr()
   * @generated
   */
  int EVO_XOR = 8;

  /**
   * The feature id for the '<em><b>Left Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_XOR__LEFT_ELEMENT = EVO_ABSTRACT_TERM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_XOR__RIGHT_ELEMENT = EVO_ABSTRACT_TERM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Evo XOr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_XOR_FEATURE_COUNT = EVO_ABSTRACT_TERM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoAndImpl <em>Evo And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoAndImpl
   * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoAnd()
   * @generated
   */
  int EVO_AND = 9;

  /**
   * The feature id for the '<em><b>Left Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_AND__LEFT_ELEMENT = EVO_ABSTRACT_TERM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_AND__RIGHT_ELEMENT = EVO_ABSTRACT_TERM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Evo And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVO_AND_FEATURE_COUNT = EVO_ABSTRACT_TERM_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link de.evorepair.logic.evoLogicLanguage.CommandDocument <em>Command Document</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Document</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.CommandDocument
   * @generated
   */
  EClass getCommandDocument();

  /**
   * Returns the meta object for the containment reference list '{@link de.evorepair.logic.evoLogicLanguage.CommandDocument#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.CommandDocument#getImports()
   * @see #getCommandDocument()
   * @generated
   */
  EReference getCommandDocument_Imports();

  /**
   * Returns the meta object for the containment reference '{@link de.evorepair.logic.evoLogicLanguage.CommandDocument#getFormula <em>Formula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Formula</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.CommandDocument#getFormula()
   * @see #getCommandDocument()
   * @generated
   */
  EReference getCommandDocument_Formula();

  /**
   * Returns the meta object for class '{@link de.evorepair.logic.evoLogicLanguage.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link de.evorepair.logic.evoLogicLanguage.Import#getImportURI <em>Import URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import URI</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.Import#getImportURI()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportURI();

  /**
   * Returns the meta object for class '{@link de.evorepair.logic.evoLogicLanguage.EvoFormula <em>Evo Formula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evo Formula</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoFormula
   * @generated
   */
  EClass getEvoFormula();

  /**
   * Returns the meta object for the containment reference list '{@link de.evorepair.logic.evoLogicLanguage.EvoFormula#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoFormula#getVariables()
   * @see #getEvoFormula()
   * @generated
   */
  EReference getEvoFormula_Variables();

  /**
   * Returns the meta object for the containment reference '{@link de.evorepair.logic.evoLogicLanguage.EvoFormula#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Term</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoFormula#getTerm()
   * @see #getEvoFormula()
   * @generated
   */
  EReference getEvoFormula_Term();

  /**
   * Returns the meta object for class '{@link de.evorepair.logic.evoLogicLanguage.EvoVariable <em>Evo Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evo Variable</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoVariable
   * @generated
   */
  EClass getEvoVariable();

  /**
   * Returns the meta object for class '{@link de.evorepair.logic.evoLogicLanguage.EvoVariableTerm <em>Evo Variable Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evo Variable Term</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoVariableTerm
   * @generated
   */
  EClass getEvoVariableTerm();

  /**
   * Returns the meta object for the reference '{@link de.evorepair.logic.evoLogicLanguage.EvoVariableTerm#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoVariableTerm#getVariable()
   * @see #getEvoVariableTerm()
   * @generated
   */
  EReference getEvoVariableTerm_Variable();

  /**
   * Returns the meta object for class '{@link de.evorepair.logic.evoLogicLanguage.EvoArbitratyFeatureVariable <em>Evo Arbitraty Feature Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evo Arbitraty Feature Variable</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoArbitratyFeatureVariable
   * @generated
   */
  EClass getEvoArbitratyFeatureVariable();

  /**
   * Returns the meta object for the reference '{@link de.evorepair.logic.evoLogicLanguage.EvoArbitratyFeatureVariable#getFeature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Feature</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoArbitratyFeatureVariable#getFeature()
   * @see #getEvoArbitratyFeatureVariable()
   * @generated
   */
  EReference getEvoArbitratyFeatureVariable_Feature();

  /**
   * Returns the meta object for class '{@link de.evorepair.logic.evoLogicLanguage.EvoAbstractTerm <em>Evo Abstract Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evo Abstract Term</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoAbstractTerm
   * @generated
   */
  EClass getEvoAbstractTerm();

  /**
   * Returns the meta object for class '{@link de.evorepair.logic.evoLogicLanguage.EvoOr <em>Evo Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evo Or</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoOr
   * @generated
   */
  EClass getEvoOr();

  /**
   * Returns the meta object for the containment reference '{@link de.evorepair.logic.evoLogicLanguage.EvoOr#getLeftElement <em>Left Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left Element</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoOr#getLeftElement()
   * @see #getEvoOr()
   * @generated
   */
  EReference getEvoOr_LeftElement();

  /**
   * Returns the meta object for the containment reference '{@link de.evorepair.logic.evoLogicLanguage.EvoOr#getRightElement <em>Right Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Element</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoOr#getRightElement()
   * @see #getEvoOr()
   * @generated
   */
  EReference getEvoOr_RightElement();

  /**
   * Returns the meta object for class '{@link de.evorepair.logic.evoLogicLanguage.EvoXOr <em>Evo XOr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evo XOr</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoXOr
   * @generated
   */
  EClass getEvoXOr();

  /**
   * Returns the meta object for the containment reference '{@link de.evorepair.logic.evoLogicLanguage.EvoXOr#getLeftElement <em>Left Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left Element</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoXOr#getLeftElement()
   * @see #getEvoXOr()
   * @generated
   */
  EReference getEvoXOr_LeftElement();

  /**
   * Returns the meta object for the containment reference '{@link de.evorepair.logic.evoLogicLanguage.EvoXOr#getRightElement <em>Right Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Element</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoXOr#getRightElement()
   * @see #getEvoXOr()
   * @generated
   */
  EReference getEvoXOr_RightElement();

  /**
   * Returns the meta object for class '{@link de.evorepair.logic.evoLogicLanguage.EvoAnd <em>Evo And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evo And</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoAnd
   * @generated
   */
  EClass getEvoAnd();

  /**
   * Returns the meta object for the containment reference '{@link de.evorepair.logic.evoLogicLanguage.EvoAnd#getLeftElement <em>Left Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left Element</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoAnd#getLeftElement()
   * @see #getEvoAnd()
   * @generated
   */
  EReference getEvoAnd_LeftElement();

  /**
   * Returns the meta object for the containment reference '{@link de.evorepair.logic.evoLogicLanguage.EvoAnd#getRightElement <em>Right Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right Element</em>'.
   * @see de.evorepair.logic.evoLogicLanguage.EvoAnd#getRightElement()
   * @see #getEvoAnd()
   * @generated
   */
  EReference getEvoAnd_RightElement();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EvoLogicLanguageFactory getEvoLogicLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.evorepair.logic.evoLogicLanguage.impl.CommandDocumentImpl <em>Command Document</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.logic.evoLogicLanguage.impl.CommandDocumentImpl
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getCommandDocument()
     * @generated
     */
    EClass COMMAND_DOCUMENT = eINSTANCE.getCommandDocument();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND_DOCUMENT__IMPORTS = eINSTANCE.getCommandDocument_Imports();

    /**
     * The meta object literal for the '<em><b>Formula</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND_DOCUMENT__FORMULA = eINSTANCE.getCommandDocument_Formula();

    /**
     * The meta object literal for the '{@link de.evorepair.logic.evoLogicLanguage.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.logic.evoLogicLanguage.impl.ImportImpl
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORT_URI = eINSTANCE.getImport_ImportURI();

    /**
     * The meta object literal for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoFormulaImpl <em>Evo Formula</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoFormulaImpl
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoFormula()
     * @generated
     */
    EClass EVO_FORMULA = eINSTANCE.getEvoFormula();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVO_FORMULA__VARIABLES = eINSTANCE.getEvoFormula_Variables();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVO_FORMULA__TERM = eINSTANCE.getEvoFormula_Term();

    /**
     * The meta object literal for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoVariableImpl <em>Evo Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoVariableImpl
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoVariable()
     * @generated
     */
    EClass EVO_VARIABLE = eINSTANCE.getEvoVariable();

    /**
     * The meta object literal for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoVariableTermImpl <em>Evo Variable Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoVariableTermImpl
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoVariableTerm()
     * @generated
     */
    EClass EVO_VARIABLE_TERM = eINSTANCE.getEvoVariableTerm();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVO_VARIABLE_TERM__VARIABLE = eINSTANCE.getEvoVariableTerm_Variable();

    /**
     * The meta object literal for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoArbitratyFeatureVariableImpl <em>Evo Arbitraty Feature Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoArbitratyFeatureVariableImpl
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoArbitratyFeatureVariable()
     * @generated
     */
    EClass EVO_ARBITRATY_FEATURE_VARIABLE = eINSTANCE.getEvoArbitratyFeatureVariable();

    /**
     * The meta object literal for the '<em><b>Feature</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVO_ARBITRATY_FEATURE_VARIABLE__FEATURE = eINSTANCE.getEvoArbitratyFeatureVariable_Feature();

    /**
     * The meta object literal for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoAbstractTermImpl <em>Evo Abstract Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoAbstractTermImpl
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoAbstractTerm()
     * @generated
     */
    EClass EVO_ABSTRACT_TERM = eINSTANCE.getEvoAbstractTerm();

    /**
     * The meta object literal for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoOrImpl <em>Evo Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoOrImpl
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoOr()
     * @generated
     */
    EClass EVO_OR = eINSTANCE.getEvoOr();

    /**
     * The meta object literal for the '<em><b>Left Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVO_OR__LEFT_ELEMENT = eINSTANCE.getEvoOr_LeftElement();

    /**
     * The meta object literal for the '<em><b>Right Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVO_OR__RIGHT_ELEMENT = eINSTANCE.getEvoOr_RightElement();

    /**
     * The meta object literal for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoXOrImpl <em>Evo XOr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoXOrImpl
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoXOr()
     * @generated
     */
    EClass EVO_XOR = eINSTANCE.getEvoXOr();

    /**
     * The meta object literal for the '<em><b>Left Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVO_XOR__LEFT_ELEMENT = eINSTANCE.getEvoXOr_LeftElement();

    /**
     * The meta object literal for the '<em><b>Right Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVO_XOR__RIGHT_ELEMENT = eINSTANCE.getEvoXOr_RightElement();

    /**
     * The meta object literal for the '{@link de.evorepair.logic.evoLogicLanguage.impl.EvoAndImpl <em>Evo And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoAndImpl
     * @see de.evorepair.logic.evoLogicLanguage.impl.EvoLogicLanguagePackageImpl#getEvoAnd()
     * @generated
     */
    EClass EVO_AND = eINSTANCE.getEvoAnd();

    /**
     * The meta object literal for the '<em><b>Left Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVO_AND__LEFT_ELEMENT = eINSTANCE.getEvoAnd_LeftElement();

    /**
     * The meta object literal for the '<em><b>Right Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVO_AND__RIGHT_ELEMENT = eINSTANCE.getEvoAnd_RightElement();

  }

} //EvoLogicLanguagePackage
