/*
 * generated by Xtext 2.12.0
 */
package de.evorepair.feature.expression.ide


/**
 * Use this class to register ide components.
 */
class ExpressionDslIdeModule extends AbstractExpressionDslIdeModule {
}
