/**
 * generated by Xtext 2.11.0
 */
package de.evorepair.evolution.operation.ide;

import com.google.inject.Injector;
import de.evorepair.evolution.operation.EvoOperationDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EvoOperationDslIdeSetup extends EvoOperationDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from EvoOperationDslRuntimeModule to Module"
      + "\nType mismatch: cannot convert from EvoOperationDslIdeModule to Module");
  }
}
