/*
 * generated by Xtext 2.11.0
 */
package de.evorepair.logic.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEvoLogicLanguageScopeProvider extends DelegatingScopeProvider {
}
