/*
 * generated by Xtext 2.11.0
 */
package de.evorepair.evolution.operation.ui;

import com.google.inject.Injector;
import de.evorepair.evolution.operation.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EvoOperationDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DslActivator.getInstance().getInjector(DslActivator.DE_EVOREPAIR_EVOLUTION_OPERATION_EVOOPERATIONDSL);
	}
	
}
